### ISSUE TITLE
Figure out what to do with OpenShift tests

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#10]
##### SUMMARY

Currently, the tests run by `ansible-test` (e.g. `ansible-test integration --docker -v --color`) are running on OpenShift 3.9.0 (`openshift/origin:v3.9.0`), which has been out of support for some time.

The current release of OpenShift 3 is 3.11, though the Docker Hub image for that version is 2 years old (https://hub.docker.com/r/openshift/origin/tags), and also uses Kubernetes 1.11 as a base, which has not been supported upstream for some time either (see the [K8s version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/)).

It would be good to use a supported image for the CI environment k8s cluster testing—for Operator SDK, the `bsycorp/kind` (see [tags](https://hub.docker.com/r/bsycorp/kind/tags)). There's also the official [SIG kind](https://kind.sigs.k8s.io), which I've successfully used on other ansible testing projects ([example](https://github.com/geerlingguy/ansible-for-kubernetes/blob/master/tests/cluster-aws-eks.sh#L32-L42)).

Ideally, we would have something from CRC or OKD that's equivalent to the single-container approach in `openshift/origin`, but I'm not sure if there's any timeline for something CI/local-friendly for OpenShift 4.x.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

ansible-test / CI tests

**Comment by fabianvf** [comment]
yeah, I like the idea of moving to the official kind tool. Basically our test pipeline would then be

`install kind -> kind create cluster -> invoke tests`

I'd hazard a guess that a lot of what ansible-test gets you doesn't help us a ton since we have pretty simple host management and mostly just need to interact with a kubernetes API. In the long run I plan to make a kind molecule driver, but for now we could pretty easily just stand it up manually and either invoke molecule with the delegated driver or just run the test playbook by hand

**Comment by geerlingguy** [comment]
@fabianvf - Ha, just realized @ssbarnea closed https://github.com/ansible-community/molecule/issues/2043 a few days ago, which was your initial idea of putting a kind driver into molecule itself.

Right now in the above PR (#22), I'm pursuing setting up Kind via a GitHub action, then using the `delegated` driver, but long-term I think it would be nice for all the downstream projects testing with Kubernetes and Ansible to be able to have a `kind` driver for Molecule.

**Comment by geerlingguy** [comment]
Reopening—remembered that moving to kind for some of the integration tests is only part of this issue's impetus; we still need to figure out:

  - If we want to move the remaining bits from the ansible-test integration test over to the molecule test (so it runs on a more modern Kubernetes version)
  - If there's any more modern OpenShift 4.x+ environment we can use in CI so we can still test things (especially the openshift/OKD-specific tests) on an OpenShift cluster instead of a plain Kubernetes cluster (right now the tests are on an old and now-unmaintained openshift 3.x container image).
  - If we do move things into molecule, what happens to the code coverage reporting that's currently in the 'integration' test suite—will that still function at all?

**Comment by fabianvf** [comment]
>     * If we want to move the remaining bits from the ansible-test integration test over to the molecule test (so it runs on a more modern Kubernetes version)

I vote yes

>     * If there's any more modern OpenShift 4.x+ environment we can use in CI so we can still test things (especially the openshift/OKD-specific tests) on an OpenShift cluster instead of a plain Kubernetes cluster (right now the tests are on an old and now-unmaintained openshift 3.x container image).

I think the only way we could do this is to hook into the openshift prow system, which may not be possible from this org. We could also just test against upstream kubernetes and if OpenShift deems it a priority we could set up a downstream repo that has a few additional openshift-specific tests. Since the basic APIs between openshift and kubernetes are the same and there's no good CI friendly openshift solution, I don't know that we need to make it a priority in this repo.

>     * If we do move things into molecule, what happens to the code coverage reporting that's currently in the 'integration' test suite—will that still function at all?

Probably not, though we can set it up ourselves. I wonder how ansible-test gathers that information, we may be able to do whatever they are doing.

**Comment by geerlingguy** [comment]
@fabianvf - I've also heard that there's a possibility that `ansible-test` will someday (not sure when) be one of the backends to molecule, so molecule could run whatever integration tests are needed. Not sure how that will work, or when it will be worked on, but that could make it simpler to run all the proper tests through one tool.

**Comment by geerlingguy** [comment]
One proposal: We split out into a `community.openshift` collection.

**Comment by geerlingguy** [comment]
See also #175 (which is kinda-sorta a dupe of #48, but more formal and written after some discussion between @tima, @fabianvf, and myself).

**Comment by geerlingguy** [comment]
Moving this issue over to https://github.com/ansible-collections/community.okd/issues/2
