### ISSUE TITLE
Mock calls to community.k8s

### ISSUE THREAD

**Issue by stiller-leser** [ansible-collections/community.kubernetes#198]
##### SUMMARY

This is more a request about the feasibility with molecule. If it is possible, I'd be happy to document this. I have two ansible roles, where role B depends on role A. Both roles use calls to `community.k8s.*` to configure the state of a K8s cluster. Since role B is dependend on k8s resources created by role A, I can not test role B without role A. 

I wonder though, if it is somehow possible to mock the calls in the role B tasks that retrieve resources created by role A (e.g. mock a certain `community.kubernetes.k8s_info`) call to always return a known good state?

Best regards,
stiller-leser

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

README.md

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = None
  configured module search path = ['/Users/myUser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

**Comment by geerlingguy** [comment]
I'm not sure if it would be possible to mock data from `k8s_info`—at least, there's no mechanism for doing so that I can think of. You'd need an actual cluster running that you could query to get any information back from the Kubernetes API, and I don't think there's a mechanism in Ansible for building mock data to return from a module.

One option you have is you could write a custom module with the same interface as `k8s_info` that always returns data in the format you expect, and have a task that is conditional on whether it's running in a test environment that gets the data from your custom module rather than this collection's `k8s_info` module.

**Comment by stiller-leser** [comment]
Thank you for the answer, I was expecting something like this. It would be kinda cool to have something like:
```
  community.kubernetes.k8s_info:
    kind: Pod
    namespace: "{{ ansible_operator_meta.namespace }}"
    mock:
      when: run_from_molecule
      data: {
        myMockData
      }
  register: pod
```
Instead of developing a module with the same API like `community.k8s`, I could also use `set_fact` for `pod` - My goal was using the same task in order to prevent copy and paste errors.

**Comment by tima** [comment]
Mock interfaces is not something we can to take on in this collection. It's not something the Ansible community has approached testing traditionally opting to use its automation to setup test systems and work against that. If Ansible where to  begin to support mock data to return from a module that mechanism would get implemented in the Ansible core and not a collection. Besides the `set_fact` approach, you could use a variable file you pull into your test runs. If you really wanted to use mocking data for your testing I'd follow what @geerlingguy suggested write a custom module with the same name (but different namespace) and interface that always returns data you expect.
