### ISSUE TITLE
support for community.kubernetes.kubeadm  to create cluster?

### ISSUE THREAD

**Issue by netw0rm** [ansible-collections/community.kubernetes#329]

**Comment by netw0rm** [comment]
like docker_swarm.

**Comment by Akasurde** [comment]
I think there are already playbooks to create K8S clusters like this https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/

**Comment by geerlingguy** [comment]
There are also roles like `geerlingguy.kubernetes` that install via `kubeadm` (https://github.com/geerlingguy/ansible-role-kubernetes), and playbooks to install specific distributions like Rancher's K3s: https://github.com/k3s-io/k3s-ansible

In the past, we thought about this and decided that we didn't want to try to support K8s installation in this collection since there are at least dozens (if not hundreds) of different ways to do it, many of them already well-supported elsewhere.

**Comment by tima** [comment]
Closing based on feedback from @geerlingguy and @Akasurde.

**Comment by netw0rm** [comment]
ok
