### ISSUE TITLE
What to do about vendor-specific Kubernetes features

### ISSUE THREAD

**Issue by fabianvf** [ansible-collections/community.kubernetes#48]
##### SUMMARY
Currently in the `k8s` module we do a bit of special casing for `Projects`, an OpenShift-specific resource, and there is another PR raised to do something similar for `BuildRequests`, also OpenShift-specific. As a project, we should decide whether we want to accept and support vendor-specific Kubernetes resources, or if we should target vanilla Kubernetes and encourage other vendors to add their own collections (perhaps that build off this one, if that is possible) that handle the special-casing of their resources. If we decide the latter, we should also refactor the OpenShift-specific code out and move it to an OpenShift specific collection.

We could also consider a hybrid, where we remove the vendor-specific bits from the core `k8s` modules but allow additional vendor-specific modules, so instead of special casing Projects in the `k8s` module, we may have an `openshift` or `openshift_project` module that properly handles the behavior.

I'd be happy with any of these decisions, but I think it would be good to have general guidance documented, to avoid the perception of favouritism between vendors.

##### ISSUE TYPE
- Documentation Report

**Comment by geerlingguy** [comment]
> I'd be happy with any of these decisions, but I think it would be good to have general guidance documented, to avoid the perception of favouritism between vendors.

Agreed. From one point, the collection is named `kubernetes`, so it would make some sense to limit it to the general kubernetes structure.

However we have ideas of incorporating things like a Helm module (#28), and as you mention there is already some nominal OpenShift-specific support... so I think I'd be okay with incorporating some wider Kubernetes functionality maybe.

If we do expand OpenShift-specific support I think we should have two rules in place:

  - We can't incorporate anything that can't be tested with the current version of OpenShift (e.g. we would need to figure out what to do with #10—we certainly can't run CRC in CI).
  - The OpenShift functionality should be split from the `k8s` modules and utils, because otherwise those modules will become overly complex and even harder to test.

**Comment by geerlingguy** [comment]
Also linking #39 here as that's the BuildRequests PR.

**Comment by geerlingguy** [comment]
And finally, wanted to mention the kubevirt modules (e.g. [`kubevirt_vm`](https://docs.ansible.com/ansible/latest/modules/kubevirt_vm_module.html)), because they are also coupled tightly to the current k8s module libraries, though they are not in this collection.

**Comment by fabianvf** [comment]
I'm currently leaning to using a separate collection for vendor-specific behavior, but I have one major concern - is it currently possible to share code across collections, or would we need to copy the module_utils content to get access to those classes/methods?

**Comment by jamescassell** [comment]
I'd hope there's a way to declare cross collection deps, to make them available. Cc @gundalow

**Comment by geerlingguy** [comment]
@fabianvf / @jamescassell - I _believe_ you can just declare a dependency in your `galaxy.yml` and as long as the other collection is present, you can use code from it (module_utils or modules). I think the `libvirt_*` modules inside `community.general` actually depend on code in this collection already. Not sure if it's actually working or not, but that should be possible.

**Comment by geerlingguy** [comment]
Related #175

**Comment by tima** [comment]
We're moving ahead with the proposal described in #175 and have established an [ansible-collections/community.okd](https://github.com/ansible-collections/community.okd) collection. Closing this ticket and will track progress through task specific and meta issues like #187 and ansible-collections/community.okd#6.
