### ISSUE TITLE
support for synchronize / rsync module

### ISSUE THREAD

**Issue by coreyoconnor** [ansible-collections/community.kubernetes#74]
##### SUMMARY

Support for the `synchronize` (rsync front end) module in the kubectl and oc connection plugins. Or create an equivalent.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- oc
- kubectl
- (external) synchronize

##### ADDITIONAL INFORMATION

This likely requires modification of the `synchronize` module. I'm not even sure this is even possible! :)

An alternative, which might be equivalent, is support for oc/kubectl `cp` command.

references:

- https://serverfault.com/questions/741670/rsync-files-to-a-kubernetes-pod

**Comment by geerlingguy** [comment]
It would probably be easier to find a way to support the `kubectl cp` command rather than integrate with `synchronize`.

**Comment by coreyoconnor** [comment]
Forgot to mention: I'm currently using the `copy` module. Which works fine. A goal is to have some incremental copy functionality. Which the standard `copy` module does not appear to have.

**Comment by tima** [comment]
As the original author of the synchronize module I implore you not to do this for the love of humanity.  That module has long suffered from scope creep and is a Frankenstein monster. It makes me sad every time I look at it.

If anything, this should be a new module for express purpose of rsync'ing between a local system to a pod. I'd advise against it though. You need to be very cognizant that this is a lot more complicated than it seems on the surface by that serverfault post. The container must have rsync present on it. If not, you need need to do some serious acrobatics to fake it [like they do with the `oc rsync` command](https://docs.openshift.com/container-platform/4.3/nodes/containers/nodes-containers-copying-files.html) and that has its limitations.

So you either must require having rsync on each and ever pod or you have to be OK with the limitations of the tar and copy scheme they built into that command. 

Let me tell you from experience that trying to wrap or replicate all of the possible ways of using rsync into a module is like trying to contain the ocean.

One of the most difficult things I realized about rsync when developing the synchronize module is that rsync has its own transport and connectivity subsystem that completely circumvents the one Ansible is running for every single other module in existence. Trying to capture and handle (fake really) how Ansible was handling its connectivity was a bear. The result of this is that over time, as things inside the engine got refactored, enhanced and expanded, the module can break and needs constant care to keep it (no pun intended) synced. This was particularly painful for the Ansible core developers while they were working on v2.0-2.4 and doing extensive work to optimize Ansible's transport and connectivity layer. I think they're still made at me from having to deal with all of that. This is partially why I don't even recognize that code in there either. 

If you do create this module look forward to getting "bugs" that they can't sync files between to different K8s clusters using a different pass-phrase protect ssh key using the rsync protocol and other madness.

I digress though. 

Realizing the brittle and tenuous nature of circumventing Ansible's system and the extent of magical incantations you can cast with rsync, I stated that module had a limited scope of what I could determine was the most common for easily syncing files between two Ansible hosts (I was ambitious and went for remote to delegate syncing also), but is was not meant to do all the things rsync can do. I was very explicit about that when I released and repeated it often. This is exactly why I named the module synchronize and not rsync. 

Despite my conscious module naming and stated limited scope, I constantly got hit up with "bug reports" that "rsync does X but not your module" because they were throwing some curve ball at the module that was outside of how Ansible was operating that they expected to override or the module to just know. I said "no, just use `command: rsync`" often which wasn't usually received well. Ansible being open source and me not being a committer, a lot of things I initially resisted to keep the module's scope focused were accepted and merged later. Hence, the Frankenstein monster we have today that no one want to maintain and is being banished to the ansible.community collection.

So just don't do it.

**Comment by geerlingguy** [comment]
I think, based on @tima's warnings above, and also taking another look at the option, I don't think this feature is something we'd want to support through k8s connections; even outside of this collection's context, it's not too common to see people trying to use `rsync` through Kubernetes directly (as there are other mechanisms for copying files into Kubernetes containers and PVs).

I'm going to close the issue, and recommend using `copy`, or considering opening a new issue with some sort of request for how you'd like to see something like `kubectl cp` more strongly supported by this collection.
