### ISSUE TITLE
Rename repo to community.kubernetes

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.kubernetes#76]
##### SUMMARY
Hi,
To be more consistent with the other repos https://github.com/ansible-collections/ I'd like to rename this GitHub Repo to be `community.kubernetes`

* Old URLs for issues and PRs will still work
* Old git URLs will work, though it will be good to update them locally
* We will need to update the URLs in `galaxy.yml`

Are you happy with this?
##### ISSUE TYPE
- Bug Report

**Comment by geerlingguy** [comment]
@gundalow - Specifically to the third point ("We will need to update the URLs in `galaxy.yml`") — until that is done and a new version is published, would that mean the link from the Galaxy collection page for the repo would be pointing at the wrong location? I presume that would still redirect too since GitHub manages the redirect.

I just want to make sure if I rename the repository nothing else breaks.

**Comment by gundalow** [comment]
GitHub maintains redirects, so nothing should be broken
Notice that https://github.com/ansible-collections/mongodb redirects to `community.mongodb`

**Comment by geerlingguy** [comment]
I've renamed the repo itself, and just submitted a PR to update all the relevant links and settings in the collection metadata: https://github.com/ansible-collections/community.kubernetes/pull/81
